import { NextRequest, NextResponse } from 'next/server';
import { getSupabaseAdminClient } from '@/lib/supabase';

// Research-relevant columns only — excludes internal/operational fields
// (id, staging_id, word_count, char_count, review_notes, review_time_ms, source_corpus)
const EXPORT_SELECT = [
  'card_id', 'type', 'is_phishing', 'difficulty', 'technique',
  'from_address', 'subject', 'body', 'auth_status', 'reply_to',
  'attachment_name', 'sent_at', 'highlights', 'clues', 'explanation',
  'ai_model', 'ai_preprocessing_version', 'approved_at',
].join(', ');

type ExportRow = Record<string, unknown>;

export async function GET(req: NextRequest) {
  const format = req.nextUrl.searchParams.get('format') ?? 'json';

  const supabase = getSupabaseAdminClient();
  const { data, error } = await supabase
    .from('cards_real')
    .select(EXPORT_SELECT)
    .order('approved_at', { ascending: true });

  if (error) return NextResponse.json({ error: error.message }, { status: 500 });

  // Double cast required — Supabase can't infer column types from a dynamic select string
  const rows = (data as unknown as ExportRow[] | null) ?? [];
  if (!rows.length) return NextResponse.json({ error: 'No approved cards to export.' }, { status: 404 });

  const date = new Date().toISOString().slice(0, 10);
  const filename = `retro-phish-v1-${date}`;

  if (format === 'csv') return exportCsv(rows, filename);
  if (format === 'jsonl') return exportJsonl(rows, filename);
  return exportJson(rows, filename);
}

function buildMetadata(data: ExportRow[]) {
  const phishing = data.filter((c) => c.is_phishing);
  const legit = data.filter((c) => !c.is_phishing);

  const byTechnique: Record<string, number> = {};
  for (const card of phishing) {
    const t = (card.technique as string) ?? 'unknown';
    byTechnique[t] = (byTechnique[t] ?? 0) + 1;
  }

  const byDifficulty: Record<string, number> = {};
  for (const card of data) {
    const d = (card.difficulty as string) ?? 'unknown';
    byDifficulty[d] = (byDifficulty[d] ?? 0) + 1;
  }

  return {
    dataset: 'Retro Phish v1',
    description: 'AI-generated phishing awareness dataset. Cards generated by Claude (Haiku + Sonnet). Linguistic quality is held constant — technique is the primary independent variable. Study question: which phishing techniques do humans miss most when AI eliminates poor grammar as a detection signal?',
    exported_at: new Date().toISOString(),
    total_cards: data.length,
    phishing_cards: phishing.length,
    legit_cards: legit.length,
    technique_breakdown: byTechnique,
    difficulty_breakdown: byDifficulty,
    source: 'https://retro-phish.scottaltiparmak.com',
    methodology: 'https://retro-phish.scottaltiparmak.com/methodology',
    author: 'Scott Altiparmak — scottaltiparmak.com',
  };
}

function exportJson(data: ExportRow[], filename: string): NextResponse {
  const output = {
    metadata: buildMetadata(data),
    cards: data,
  };
  return NextResponse.json(output, {
    headers: {
      'Content-Disposition': `attachment; filename="${filename}.json"`,
    },
  });
}

function exportJsonl(data: ExportRow[], filename: string): NextResponse {
  const lines = data.map((row) => JSON.stringify(row)).join('\n');
  return new NextResponse(lines, {
    headers: {
      'Content-Type': 'application/jsonl',
      'Content-Disposition': `attachment; filename="${filename}.jsonl"`,
    },
  });
}

function exportCsv(data: ExportRow[], filename: string): NextResponse {
  const columns = Object.keys(data[0]);
  const header = columns.join(',');

  const rows = data.map((row) =>
    columns.map((col) => {
      const v = row[col];
      if (v === null || v === undefined) return '';
      // Arrays (highlights, clues): join with pipe separator
      if (Array.isArray(v)) return `"${(v as string[]).join(' | ').replace(/"/g, '""')}"`;
      if (typeof v === 'string') return `"${v.replace(/"/g, '""')}"`;
      return String(v);
    }).join(',')
  );

  const csv = [header, ...rows].join('\n');
  return new NextResponse(csv, {
    headers: {
      'Content-Type': 'text/csv',
      'Content-Disposition': `attachment; filename="${filename}.csv"`,
    },
  });
}
