import { parse } from 'csv-parse/sync';
import { readFileSync, writeFileSync } from 'fs';

const csv = readFileSync(process.argv[2], 'utf-8');
const records: Record<string, string>[] = parse(csv, { columns: true, skip_empty_lines: true, relax_column_count: true });

function escSql(val: string | null | undefined): string {
  if (val === null || val === undefined || val === '') return 'NULL';
  return `'${val.replace(/'/g, "''")}'`;
}

function escBool(val: string | null | undefined): string {
  if (val === null || val === undefined || val === '') return 'NULL';
  return val === 'true' || val === 't' ? 'TRUE' : 'FALSE';
}

function escInt(val: string | null | undefined): string {
  if (val === null || val === undefined || val === '') return 'NULL';
  return val;
}

function escArray(val: string | null | undefined): string {
  if (val === null || val === undefined || val === '' || val === '{}') return 'NULL';
  // Supabase CSV exports arrays as {val1,val2,...}
  // Convert to ARRAY['val1','val2'] syntax
  const inner = val.replace(/^\{/, '').replace(/\}$/, '');
  if (!inner) return 'NULL';
  const items = inner.split(',').map((s: string) => {
    const trimmed = s.replace(/^"|"$/g, '').replace(/'/g, "''");
    return `'${trimmed}'`;
  });
  return `ARRAY[${items.join(',')}]::TEXT[]`;
}

const lines: string[] = [];
lines.push('-- Seed data: subset of freeplay cards for dev/test environment');
lines.push(`-- Exported from prod on ${new Date().toISOString().split('T')[0]}`);
lines.push('-- Auto-generated by scripts/csv-to-seed.ts');
lines.push('');
lines.push("INSERT INTO dataset_versions (version, description)");
lines.push("VALUES ('v1', 'Initial dataset')");
lines.push("ON CONFLICT (version) DO NOTHING;");
lines.push('');

// Default missing difficulty to 'medium' (legit cards in prod have null difficulty)
for (const r of records) {
  const d = r.difficulty?.trim();
  if (!d || !['easy', 'medium', 'hard', 'extreme'].includes(d)) {
    r.difficulty = 'medium';
  }
}
const validRecords = records;
console.log(`Processing ${records.length} cards`);

for (const r of validRecords) {
  lines.push(`INSERT INTO cards_real (card_id, type, is_phishing, difficulty, from_address, subject, body, technique, secondary_technique, grammar_quality, prose_fluency, personalization_level, contextual_coherence, highlights, clues, explanation, source_corpus, dataset_version)`);
  lines.push(`VALUES (${escSql(r.card_id)}, ${escSql(r.type)}, ${escBool(r.is_phishing)}, ${escSql(r.difficulty)}, ${escSql(r.from_address)}, ${escSql(r.subject)}, ${escSql(r.body)}, ${escSql(r.technique)}, ${escSql(r.secondary_technique)}, ${escInt(r.grammar_quality)}, ${escInt(r.prose_fluency)}, ${escInt(r.personalization_level)}, ${escInt(r.contextual_coherence)}, ${escArray(r.highlights)}, ${escArray(r.clues)}, ${escSql(r.explanation)}, ${escSql(r.source_corpus)}, ${escSql(r.dataset_version)})`);
  lines.push('ON CONFLICT (card_id) DO NOTHING;');
  lines.push('');
}

const out = process.argv[3] || 'supabase/seed.sql';
writeFileSync(out, lines.join('\n'));
console.log(`Written ${validRecords.length} cards to ${out}`);
